steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sanguine-willow-436015-k8/prod-alphamarch', '.']
    env:
      - 'DOCKER_BUILDKIT=1'
    id: 'build-image'

  - name: 'gcr.io/cloud-builders/compose'
    args: ['build']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sanguine-willow-436015-k8/prod-alphamarch']
    id: 'push-image'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'prod-alphamarch'
      - '--image'
      - 'gcr.io/sanguine-willow-436015-k8/prod-alphamarch'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL},NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY},NEXT_PUBLIC_CLERK_FRONTEND_API=${_NEXT_PUBLIC_CLERK_FRONTEND_API},NEXT_PUBLIC_CLERK_SIGN_IN_URL=${_NEXT_PUBLIC_CLERK_SIGN_IN_URL},NEXT_PUBLIC_CLERK_SIGN_UP_URL=${_NEXT_PUBLIC_CLERK_SIGN_UP_URL},NEXT_PUBLIC_OPENCAGE_API_KEY=${_NEXT_PUBLIC_OPENCAGE_API_KEY},CLERK_SECRET_KEY=${_CLERK_SECRET_KEY},NEXTAUTH_SECRET=${_NEXTAUTH_SECRET},NEXTAUTH_URL=${_NEXTAUTH_URL}'
    id: 'deploy-to-cloud-run'

images:
  - 'gcr.io/sanguine-willow-436015-k8/alphamarch'