import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";

const montserrat = Montserrat({ 
  subsets: ["latin"],
  weight: [
    "300","400","500","600","700","800","900"
  ]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={montserrat.className}>{children}</body>
      </ReactQueryProvider>
    </html>
  );
}
